function createfigure1(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 14-Aug-2014 14:25:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','EELS spectrum');

% Create xlabel
xlabel({'Energy (eV)'},'FontWeight','bold','FontSize',14);

% Create ylabel
ylabel({'Counts'},'FontWeight','bold','FontSize',14);

% Create title
title({'Calibrated for 0.5eV Dispersion and 78eV offset'},...
    'FontWeight','bold',...
    'FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontWeight','bold');