function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Aug-2014 19:34:13

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[74.5591072667361 178.032052115852]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-44.9986727010164 510.20077825043]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','EELS Spectrum');

% Create xlabel
xlabel({'in eV (Calibrated to 0.5eV Dispersion)'});

% Create ylabel
ylabel({'Counts'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.670565368357484 0.824271198649684 0.206521739130435 0.0659133709981168]);

% Create arrow
annotation(figure1,'arrow',[0.4453125 0.334375],...
    [0.742301458670989 0.588330632090757]);

% Create textbox
annotation(figure1,'textbox',...
    [0.451 0.730956239870339 0.226989130434783 0.0453808752025895],...
    'String',{'Si edge at 99eV'},...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'LineStyle','none');

