function createfigure2(X1, EELS_spectrum1, Y1)
%CREATEFIGURE2(X1, EELS_SPECTRUM1, Y1)
%  X1:  vector of x data
%  EELS_SPECTRUM1:  vector of y data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Sep-2014 15:56:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YColor',[0 0 1],...
    'XMinorTick','on',...
    'XMinorGrid','on',...
    'GridLineStyle','-');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 600]);
box(axes1,'on');
hold(axes1,'all');

% Create semilogy
semilogy(X1,EELS_spectrum1,'Parent',axes1,'LineWidth',2);

% Create axes
axes2 = axes('Parent',figure1,'YTick',[-100 0 100],'YAxisLocation','right',...
    'YColor',[0 0.5 0],...
    'ColorOrder',[0 0.5 0;1 0 0;0 0.75 0.75;0.75 0 0.75;0.75 0.75 0;0.25 0.25 0.25;0 0 1],...
    'Color','none');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 600]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-100 100]);
hold(axes2,'all');

% Create plot
plot(X1,Y1,'Parent',axes2,'Marker','.','LineWidth',1,'LineStyle','none',...
    'Color',[1 0 0]);

