function [fitresult, gof] = exp1(X, EELS)
%CREATEFIT1(X,EELS)
%  Create a fit.
%
%  Data for 'exp1fit' fit:
%      X Input : X
%      Y Output: EELS
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jul-2014 13:09:55

%% Fit: 'exp1fit'.
[xData, yData] = prepareCurveData( X, EELS );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.Robust = 'Bisquare';
%opts.StartPoint = [795.757822400637 -1.88367544204257];
opts.StartPoint = [132543.049 -0.07923048];
opts.Upper = [Inf Inf];
opts.Normalize = 'on';
%opts.Exclude = [20:40];
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );