function [fitresult, gof] = exp3(l, S)
%CREATEFIT1(L,S)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : l
%      Y Output: S
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2016 15:10:29


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( l, S );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c*exp(-d*x)+e*exp(-f*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.843954121311981 0.15731272417746 0.821044571368601 0.546881519204984 0.0975404049994095 0.957506835434298];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'S vs. l', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel l
ylabel S
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel l
ylabel S
grid on


