function [fitresult, gof] = Exp_1_fit(X, EELS_spectrum)
%CREATEFIT1(X,EELS_SPECTRUM)
%  Create a fit.
%
%  Data for 'Exp_1_fit' fit:
%      X Input : X
%      Y Output: EELS_spectrum
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jul-2014 13:09:55

%% Fit: 'Exp_1_fit'.
[xData, yData] = prepareCurveData( X, EELS_spectrum );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.Robust = 'LAR';
opts.StartPoint = [795.757822400637 -1.88367544204257];
opts.Upper = [Inf Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%% Create a figure for the plots.
figure( 'Name', 'Exp_1_fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'EELS vs. X', 'exp fit', 'Location', 'NorthEast' );
% Label axes
xlabel( '(X*1024)eV' );
ylabel( 'EELS' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel( '(X*1024)eV' );
ylabel( 'EELS' );
grid on
