function [BW,maskedImage] = Ga_rich_InGaN(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 11-Sep-2017
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
if isequal(Xmax,Xmin)
    X = 0*X;
else
    X = (X - Xmin) ./ (Xmax - Xmin);
end

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Polygon drawing
xPos = [0.6589 57.6656 22.6987 13.7980 37.1093 58.3013 65.2947 80.3411 1.0828];
yPos = [0.8709 1.2947 27.7848 51.3079 71.6523 80.9768 107.2550 124.8444 128.0232];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;