function [fitresult, gof] = powerlaw_InGaAs(x, EELS_spectrum)
%CREATEFIT1(X,EELS_SPECTRUM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: EELS_spectrum
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Mar-2015 16:17:11


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, EELS_spectrum );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [132606109.742831 -1.65116115089692];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
 %figure( 'Name', 'untitled fit 1' );
 %h = plot( fitresult, xData, yData );
 %legend( h, 'EELS_spectrum vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
 %xlabel x
 %ylabel EELS_spectrum
 %grid on


