function [fitresult, gof] = abc(abc)
%CREATEFIT1(ABC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: abc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Sep-2014 16:44:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], abc );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [66.8541544648625 -0.00103881571648202];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'abc', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel( 'abc' );
grid on


