function createfigure3(X1, YMatrix1, YMatrix2)
%CREATEFIGURE3(X1, YMATRIX1, YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
 
%  Auto-generated by MATLAB on 16-Mar-2016 17:38:17
 
% Create figure
figure1 = figure;
 
% Create axes
axes1 = axes('YMinorTick','on','YScale','log');
hold(axes1,'on');
 
% Activate the left side of the axes
yyaxis(axes1,'left');
% Create multiple lines using matrix input to loglog
loglog(X1,YMatrix1,'LineWidth',2);
 
% Create ylabel
ylabel('E_{onset}-E_{artifact} (in eV)');
 
% Set the remaining axes properties
set(axes1,'YColor',[0 0.447 0.741],'YMinorTick','on','YScale','log');
%Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[10 5000]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix2,...
'MarkerFaceColor',[0.87058824300766 0.490196079015732 0],...
'LineStyle','none');
set(loglog1(1),'DisplayName','1st artefact','Marker','square');
set(loglog1(2),'DisplayName','2nd artefact','Marker','diamond');
set(loglog1(3),'DisplayName','3rd artefact','Marker','v');
set(loglog1(4),'DisplayName','4th artefact','Marker','^');
legend off
%legend([loglog1(1) loglog1(2) loglog1(3) loglog1(4)], {'1st artefact','2nd artefact','3rd artefact','4th artefact'})
% Create ylabel
ylabel('Amplitude (% of overshoot)');
 
% Set the remaining axes properties
set(axes1,'YColor',[0.85 0.325 0.098],'YMinorTick','on','YScale','log');
%Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.001 1000]);
% Create title
title({'log plot of position and amplitude of artifacts'});
 
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','LineStyleOrderIndex',4,...
'XMinorGrid','on','XMinorTick','on','XScale','log','YMinorGrid','on');
% Create legend
%legend(axes1,'show');
%%
% Create line
annotation('line',[0.644268306841902 0.697645213159984],...
[0.885131171702286 0.886131171702286],...
'Color',[0 0.447058826684952 0.74117648601532],...
'LineWidth',2);
 
% Create line
annotation('line',[0.646466278910752 0.699843185228834],...
[0.802714426079943 0.803714426079943],...
'Color',[0 0.447058826684952 0.74117648601532],...
'LineWidth',2,...
'LineStyle','-.');
 
% Create line
annotation('line',[0.645458509966506 0.698835416284588],...
[0.828781555953262 0.829781555953262],...
'Color',[0 0.447058826684952 0.74117648601532],...
'LineWidth',2,...
'LineStyle',':');
 
% Create line
annotation('line',[0.645376954292015 0.698753860610097],...
[0.856050566726324 0.857050566726324],...
'Color',[0 0.447058826684952 0.74117648601532],...
'LineWidth',2,...
'LineStyle','--');
 
