function [fitresult, gof] = exp1to1(x, y)
%CREATEFIT1(X,y)
%  Create a fit.
%
%  Data for 'exp1to1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Sep-2014 13:27:55


%% Fit: 'exp1to1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [879.128624137434 -1.03413501087542];
opts.Upper = [Inf Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'exp1to1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'exp1to1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on


