function [fitresult, gof] = polymsm2015(x)
%CREATEFIT1(X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Mar-2015 18:28:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], x );

% Set up fittype and options.
ft = fittype( 'poly8' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel x
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
ylabel x
grid on


