function [fitresult, gof, options] = Power_law(e_loss, EELS)
%CREATEFIT1(E_LOSS,LEFTE)
%  Create a fit.
%
%  Data for 'Power-law fit' fit:
%      X Input : e_loss
%      Y Output: EELS
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Aug-2015 12:37:00


%% Fit: 'Power-law fit'.
[xData, yData] = prepareCurveData( e_loss, EELS );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [611138542.29765 -1.92796518355794];
opts.Upper = [inf 0];

% Fit model to data.
[fitresult, gof, options] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'Power-law fit' );
%h = plot( fitresult, xData, yData );
%legend( h, 'EELS vs. Energy-loss', 'Power-law fit', 'Location', 'NorthEast' );
% Label axes
%xlabel Energy-loss
%ylabel EELS
%grid on