close all hidden;
clear all;
clc;

Rb=0.75;
Gb=0.75;
Bb=0.75;

Rf=0;
Gf=0;
Bf=0;


global interface 

interface(1)=figure('units','pixels',...
    'position',[10 50 1582 791],...
    'color',[Rb Gb Bb],...
    'numbertitle','off',...
    'name','Source separation',...
    'menubar','none',...
    'tag','interface');

interface(2)=uimenu('label','Help');

interface(3)=uimenu(interface(2),'label','Help me',...
            'callback','open help.pdf');
        
interface(4)=uicontrol('style','text',...
    'units','normalized',...
    'position',[0.2 0.8 0.6 0.1],...
    'string','Select a type of problem',...
    'fontsize',30,...
    'tag','type',...
    'foregroundcolor',[Rf Gf Bf],...
    'backgroundcolor',[Rb Gb Bb]);

interface(5)=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.01 0.27 0.45 0.4],...
    'string','Data analysis',...
    'fontsize',50,...
    'callback','interface_2D',...
    'backgroundcolor',[1 1 1],...
    'tag','data');

interface(6)=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.52 0.27 0.45 0.4],...
    'string','Image analysis',...
    'fontsize',50,...
    'callback','interface_3D',...
    'backgroundcolor',[1 1 1],...
    'tag','image');

interface(7)=uicontrol('style','push',...
    'units','normalized',...
    'callback','end_programm',...
    'position',[0.98 0.96 0.01 0.02],...
    'string','X',...
    'tag','end');

clear all